title: dd if=/dev/urandom of=/var/www/blog
description: "A place for musings and CTF write ups"
author:
  name: "Ben Ellett"
  email: "blog [at] benjaminellett [dot] com"
  url: "https://blog.thebluetoob.com"

baseurl: /

source: .
destination: ./_site
permalink: /:title/
paginate: 10
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "thebluetoob"
year : "2020"
google_analytics: UA-151956795-1

exclude: [bundle]